services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Cyve\PasswordManagerBundle\Command\ResetPasswordCommand:
        tags:
            - { name: 'console.command', command: 'cyve:password:reset' }

    Cyve\PasswordManagerBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    Cyve\PasswordManagerBundle\Security\:
        resource: '../../Security/*'
