services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Cyve\PasswordManagerBundle\Command\:
        resource: '../../Command/*'

    Cyve\PasswordManagerBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    Cyve\PasswordManagerBundle\Security\:
        resource: '../../Security/*'
