services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Cyve\PasswordManagerBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,CyvePasswordManagerBundle.php}'

    Cyve\PasswordManagerBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
